name: 'Motivation Action'
description: "Write to me and I'll respond with just the right🎯 message"
branding:
  icon: 'award'
  color: 'green'
inputs:
  token:
    description: |-
      Token used to authenticate with the GitHub API.
    required: false
    default: ${{ github.token }}
runs:
  using: 'node16'
  main: 'dist/index.js'
